spring.application.name=jwt-auth

server.port=8005

spring.datasource.url=jdbc:mysql://localhost:3307/taskdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret

## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

security.jwt.secret-key="0eeb7db9ba9f42c96e9719726f5bd128bef181bf7c04e96f95b560be5eac052c"
security.jwt.expiration-time=3600000